### ISSUE TITLE
ERROR: Cannot find "/pollen.css" in pollen-css@5.0.1

### ISSUE THREAD

**Issue by janwillemtulp** [hyperfocalHQ/pollen#97]
When using the URL provided in the Getting Started documentation (https://unpkg.com/pollen-css/pollen.css) there is an error: `Cannot find "/pollen.css" in pollen-css@5.0.1`

**Comment by madeleineostoja** [comment]
Looks like unpkg doesn’t resolve the `exports` from package.json. I’ll update the docs
